// Generated by gencpp from file uwb/UWBRange.msg
// DO NOT EDIT!


#ifndef UWB_MESSAGE_UWBRANGE_H
#define UWB_MESSAGE_UWBRANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace uwb
{
template <class ContainerAllocator>
struct UWBRange_
{
  typedef UWBRange_<ContainerAllocator> Type;

  UWBRange_()
    : header()
    , address(0)
    , remote_address(0)
    , stamp_us(0)
    , round_trip_time(0.0)
    , range(0.0)  {
    }
  UWBRange_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , address(0)
    , remote_address(0)
    , stamp_us(0)
    , round_trip_time(0.0)
    , range(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _address_type;
  _address_type address;

   typedef uint8_t _remote_address_type;
  _remote_address_type remote_address;

   typedef uint32_t _stamp_us_type;
  _stamp_us_type stamp_us;

   typedef float _round_trip_time_type;
  _round_trip_time_type round_trip_time;

   typedef float _range_type;
  _range_type range;




  typedef boost::shared_ptr< ::uwb::UWBRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb::UWBRange_<ContainerAllocator> const> ConstPtr;

}; // struct UWBRange_

typedef ::uwb::UWBRange_<std::allocator<void> > UWBRange;

typedef boost::shared_ptr< ::uwb::UWBRange > UWBRangePtr;
typedef boost::shared_ptr< ::uwb::UWBRange const> UWBRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb::UWBRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb::UWBRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'uwb': ['/data/SP1/catkin_ws/src/uwb/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb::UWBRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb::UWBRange_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb::UWBRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb::UWBRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb::UWBRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb::UWBRange_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb::UWBRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59f7e9a9fe44ac74dcea199a0dda5d66";
  }

  static const char* value(const ::uwb::UWBRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59f7e9a9fe44ac74ULL;
  static const uint64_t static_value2 = 0xdcea199a0dda5d66ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb::UWBRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb/UWBRange";
  }

  static const char* value(const ::uwb::UWBRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb::UWBRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 address\n\
uint8 remote_address\n\
uint32 stamp_us\n\
float32 round_trip_time\n\
float32 range\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::uwb::UWBRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb::UWBRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.address);
      stream.next(m.remote_address);
      stream.next(m.stamp_us);
      stream.next(m.round_trip_time);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct UWBRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb::UWBRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb::UWBRange_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.address);
    s << indent << "remote_address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_address);
    s << indent << "stamp_us: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stamp_us);
    s << indent << "round_trip_time: ";
    Printer<float>::stream(s, indent + "  ", v.round_trip_time);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_MESSAGE_UWBRANGE_H
