(cl:in-package uwb-msg)
(cl:export '(HEADER-VAL
          HEADER
          NUM_OF_UNITS-VAL
          NUM_OF_UNITS
          ADDRESS-VAL
          ADDRESS
          REMOTE_ADDRESS-VAL
          REMOTE_ADDRESS
          TIMESTAMP_MASTER_REQUEST_1_RECV-VAL
          TIMESTAMP_MASTER_REQUEST_1_RECV
          TIMESTAMP_SLAVE_REPLY_SEND-VAL
          TIMESTAMP_SLAVE_REPLY_SEND
          TIMESTAMP_MASTER_REQUEST_2_RECV-VAL
          TIMESTAMP_MASTER_REQUEST_2_RECV
          TIMESTAMP_MASTER_REQUEST_1-VAL
          TIMESTAMP_MASTER_REQUEST_1
          TIMESTAMP_SLAVE_REPLY-VAL
          TIMESTAMP_SLAVE_REPLY
          TIMESTAMP_MASTER_REQUEST_2-VAL
          TIMESTAMP_MASTER_REQUEST_2
))