(cl:in-package uwb-msg)
(cl:export '(HEADER-VAL
          HEADER
          ADDRESS-VAL
          ADDRESS
          REMOTE_ADDRESS-VAL
          REMOTE_ADDRESS
          STAMP_US-VAL
          STAMP_US
          ROUND_TRIP_TIME-VAL
          ROUND_TRIP_TIME
          RANGE-VAL
          RANGE
          STD_NOISE-VAL
          STD_NOISE
          PREAMBLE_ACC_COUNT-VAL
          PREAMBLE_ACC_COUNT
          FIRST_PATH_INDEX-VAL
          FIRST_PATH_INDEX
          FIRST_PATH_AMP_1-VAL
          FIRST_PATH_AMP_1
          FIRST_PATH_AMP_2-VAL
          FIRST_PATH_AMP_2
          FIRST_PATH_AMP_3-VAL
          FIRST_PATH_AMP_3
          CHANNEL_IMPULSE_RESPONSE_POWER-VAL
          CHANNEL_IMPULSE_RESPONSE_POWER
          PRF-VAL
          PRF
))