// Generated by gencpp from file uwb/UWBMultiRange.msg
// DO NOT EDIT!


#ifndef UWB_MESSAGE_UWBMULTIRANGE_H
#define UWB_MESSAGE_UWBMULTIRANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace uwb
{
template <class ContainerAllocator>
struct UWBMultiRange_
{
  typedef UWBMultiRange_<ContainerAllocator> Type;

  UWBMultiRange_()
    : header()
    , num_of_units(0)
    , address(0)
    , remote_address(0)
    , tofs()
    , ranges()  {
    }
  UWBMultiRange_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_of_units(0)
    , address(0)
    , remote_address(0)
    , tofs(_alloc)
    , ranges(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _num_of_units_type;
  _num_of_units_type num_of_units;

   typedef uint8_t _address_type;
  _address_type address;

   typedef uint8_t _remote_address_type;
  _remote_address_type remote_address;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _tofs_type;
  _tofs_type tofs;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _ranges_type;
  _ranges_type ranges;




  typedef boost::shared_ptr< ::uwb::UWBMultiRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb::UWBMultiRange_<ContainerAllocator> const> ConstPtr;

}; // struct UWBMultiRange_

typedef ::uwb::UWBMultiRange_<std::allocator<void> > UWBMultiRange;

typedef boost::shared_ptr< ::uwb::UWBMultiRange > UWBMultiRangePtr;
typedef boost::shared_ptr< ::uwb::UWBMultiRange const> UWBMultiRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb::UWBMultiRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb::UWBMultiRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'uwb': ['/data/SP1/catkin_ws/src/uwb/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb::UWBMultiRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb::UWBMultiRange_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb::UWBMultiRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb::UWBMultiRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb::UWBMultiRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb::UWBMultiRange_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb::UWBMultiRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d5b8085d2d9728e3c5038f539f7e4f5";
  }

  static const char* value(const ::uwb::UWBMultiRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d5b8085d2d9728eULL;
  static const uint64_t static_value2 = 0x3c5038f539f7e4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb::UWBMultiRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb/UWBMultiRange";
  }

  static const char* value(const ::uwb::UWBMultiRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb::UWBMultiRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 num_of_units\n\
uint8 address\n\
uint8 remote_address\n\
float32[] tofs\n\
float32[] ranges\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::uwb::UWBMultiRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb::UWBMultiRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_of_units);
      stream.next(m.address);
      stream.next(m.remote_address);
      stream.next(m.tofs);
      stream.next(m.ranges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct UWBMultiRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb::UWBMultiRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb::UWBMultiRange_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_of_units: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_of_units);
    s << indent << "address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.address);
    s << indent << "remote_address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_address);
    s << indent << "tofs[]" << std::endl;
    for (size_t i = 0; i < v.tofs.size(); ++i)
    {
      s << indent << "  tofs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tofs[i]);
    }
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ranges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_MESSAGE_UWBMULTIRANGE_H
