// Generated by gencpp from file uwb_dummy/Coordinates.msg
// DO NOT EDIT!


#ifndef UWB_DUMMY_MESSAGE_COORDINATES_H
#define UWB_DUMMY_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwb_dummy
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : coordinates()  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : coordinates(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _coordinates_type;
  _coordinates_type coordinates;




  typedef boost::shared_ptr< ::uwb_dummy::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_dummy::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::uwb_dummy::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::uwb_dummy::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::uwb_dummy::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_dummy::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_dummy::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb_dummy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'uwb_dummy': ['/data/SP1/catkin_ws/src/uwb_dummy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb_dummy::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_dummy::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_dummy::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_dummy::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_dummy::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_dummy::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_dummy::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c74c07aeada55d213db43904e2c9d02a";
  }

  static const char* value(const ::uwb_dummy::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc74c07aeada55d21ULL;
  static const uint64_t static_value2 = 0x3db43904e2c9d02aULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_dummy::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_dummy/Coordinates";
  }

  static const char* value(const ::uwb_dummy::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_dummy::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] coordinates\n\
";
  }

  static const char* value(const ::uwb_dummy::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_dummy::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_dummy::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_dummy::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "coordinates[]" << std::endl;
    for (size_t i = 0; i < v.coordinates.size(); ++i)
    {
      s << indent << "  coordinates[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.coordinates[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_DUMMY_MESSAGE_COORDINATES_H
